/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    regions: Region;
    houses: House;
    characters: Character;
    events: Event;
    storylines: Storyline;
    locations: Location;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    regions: RegionsSelect<false> | RegionsSelect<true>;
    houses: HousesSelect<false> | HousesSelect<true>;
    characters: CharactersSelect<false> | CharactersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    storylines: StorylinesSelect<false> | StorylinesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Single-admin MVP can use this as the creator display name.
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 素材名称，用于前台图集和后台列表。
   */
  title: string;
  /**
   * 前台图片替代文本。
   */
  alt: string;
  assetType:
    | 'map-base'
    | 'local-map'
    | 'event-art'
    | 'character-art'
    | 'house-sigil'
    | 'texture'
    | 'weather'
    | 'ui'
    | 'reference';
  sourceType: 'original' | 'ai-generated' | 'redrawn-reference' | 'open-license' | 'public-reference' | 'other';
  /**
   * 原始来源链接或参考链接。
   */
  sourceUrl?: string | null;
  /**
   * 作者、画师、模型来源或素材提供方。
   */
  author?: string | null;
  /**
   * 来源方、站点或授权主体。
   */
  sourceParty?: string | null;
  isAIGenerated?: boolean | null;
  /**
   * 是否参考既有视觉素材进行二次创作或重绘。
   */
  isDerivative?: boolean | null;
  licenseStatus: 'original' | 'open-license' | 'ai-generated' | 'reference-only' | 'unknown';
  riskLevel: 'low' | 'medium' | 'high';
  /**
   * 素材使用范围：本地私有原型、可进入公开候选、或上线前必须阻断。
   */
  usageScope: 'private-prototype' | 'public-ready-candidate' | 'blocked';
  /**
   * AI 生成素材时记录简要 prompt，不保存敏感密钥。
   */
  generationPromptSummary?: string | null;
  referenceNotes?: string | null;
  notes?: string | null;
  /**
   * 前台只读取 published 内容；draft 用于后台编辑。
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions".
 */
export interface Region {
  id: number;
  nameZh: string;
  nameEn: string;
  type: 'kingdom' | 'province' | 'landform' | 'sea' | 'frontier';
  description: string;
  /**
   * 内容来源线：原著 / 剧集 / 混合 / 二创注释。
   */
  sourceType: 'novel' | 'show' | 'show-canon' | 'mixed' | 'original-note';
  /**
   * 正典层级标记，前台用于显示来源标签。
   */
  canonLevel: 'book-canon' | 'show-canon' | 'mixed-canon' | 'fan-interpretation';
  /**
   * 前台只读取 published 内容；draft 用于后台编辑。
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "houses".
 */
export interface House {
  id: number;
  nameZh: string;
  nameEn: string;
  motto?: string | null;
  sigilDescription: string;
  sigil?: (number | null) | Media;
  primaryColor?: string | null;
  secondaryColor?: string | null;
  seatLocation?: (number | null) | Location;
  controlledRegions?: (number | Region)[] | null;
  /**
   * 内容来源线：原著 / 剧集 / 混合 / 二创注释。
   */
  sourceType: 'novel' | 'show' | 'show-canon' | 'mixed' | 'original-note';
  /**
   * 正典层级标记，前台用于显示来源标签。
   */
  canonLevel: 'book-canon' | 'show-canon' | 'mixed-canon' | 'fan-interpretation';
  /**
   * 前台只读取 published 内容；draft 用于后台编辑。
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  nameZh: string;
  nameEn: string;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  type:
    | 'castle'
    | 'city'
    | 'region'
    | 'fortress'
    | 'port'
    | 'sea'
    | 'road'
    | 'river'
    | 'mountain'
    | 'forest'
    | 'wall'
    | 'other';
  region?: (number | null) | Region;
  relatedHouses?: (number | House)[] | null;
  shortDescription: string;
  longDescription?: string | null;
  politicalStatus?: string | null;
  geography?: string | null;
  /**
   * MVP uses manual coordinates. Future drag editing can write into these fields.
   */
  mapPosition: {
    xPercent: number;
    yPercent: number;
    virtualX: number;
    virtualY: number;
  };
  iconType: string;
  nodeLevel: number;
  visibleZoomRange?: {
    min?: number | null;
    max?: number | null;
  };
  /**
   * Legacy MVP flag. Prefer detailLevel for V1 click behavior.
   */
  isMvpClickable?: boolean | null;
  /**
   * Controls frontend click behavior: full detail, preview panel, or map node only.
   */
  detailLevel: 'full' | 'preview' | 'node-only';
  detailSections?:
    | {
        title: string;
        body: string;
        assets?: (number | Media)[] | null;
        id?: string | null;
      }[]
    | null;
  relatedCharacters?: (number | Character)[] | null;
  relatedEvents?: (number | Event)[] | null;
  relatedAssets?: (number | Media)[] | null;
  localMap?: (number | null) | Media;
  /**
   * 内容来源线：原著 / 剧集 / 混合 / 二创注释。
   */
  sourceType: 'novel' | 'show' | 'show-canon' | 'mixed' | 'original-note';
  /**
   * 正典层级标记，前台用于显示来源标签。
   */
  canonLevel: 'book-canon' | 'show-canon' | 'mixed-canon' | 'fan-interpretation';
  /**
   * 前台只读取 published 内容；draft 用于后台编辑。
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters".
 */
export interface Character {
  id: number;
  nameZh: string;
  nameEn: string;
  aliases?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  house?: (number | null) | House;
  titles?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  shortBio: string;
  portrait?: (number | null) | Media;
  /**
   * 内容来源线：原著 / 剧集 / 混合 / 二创注释。
   */
  sourceType: 'novel' | 'show' | 'show-canon' | 'mixed' | 'original-note';
  /**
   * 正典层级标记，前台用于显示来源标签。
   */
  canonLevel: 'book-canon' | 'show-canon' | 'mixed-canon' | 'fan-interpretation';
  /**
   * 前台只读取 published 内容；draft 用于后台编辑。
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  summary: string;
  description: string;
  primaryLocation: number | Location;
  relatedLocations?: (number | Location)[] | null;
  relatedCharacters?: (number | Character)[] | null;
  relatedHouses?: (number | House)[] | null;
  relatedAssets?: (number | Media)[] | null;
  order: number;
  displayDate?: string | null;
  bookRefLabel?: string | null;
  showRefLabel?: string | null;
  isBookEvent?: boolean | null;
  isShowEvent?: boolean | null;
  isOriginalNote?: boolean | null;
  /**
   * 内容来源线：原著 / 剧集 / 混合 / 二创注释。
   */
  sourceType: 'novel' | 'show' | 'show-canon' | 'mixed' | 'original-note';
  /**
   * 正典层级标记，前台用于显示来源标签。
   */
  canonLevel: 'book-canon' | 'show-canon' | 'mixed-canon' | 'fan-interpretation';
  /**
   * 前台只读取 published 内容；draft 用于后台编辑。
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storylines".
 */
export interface Storyline {
  id: number;
  title: string;
  summary: string;
  description: string;
  relatedEvents?: (number | Event)[] | null;
  relatedLocations?: (number | Location)[] | null;
  relatedCharacters?: (number | Character)[] | null;
  relatedHouses?: (number | House)[] | null;
  /**
   * 内容来源线：原著 / 剧集 / 混合 / 二创注释。
   */
  sourceType: 'novel' | 'show' | 'show-canon' | 'mixed' | 'original-note';
  /**
   * 正典层级标记，前台用于显示来源标签。
   */
  canonLevel: 'book-canon' | 'show-canon' | 'mixed-canon' | 'fan-interpretation';
  /**
   * 前台只读取 published 内容；draft 用于后台编辑。
   */
  status: 'draft' | 'published';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'regions';
        value: number | Region;
      } | null)
    | ({
        relationTo: 'houses';
        value: number | House;
      } | null)
    | ({
        relationTo: 'characters';
        value: number | Character;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'storylines';
        value: number | Storyline;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  assetType?: T;
  sourceType?: T;
  sourceUrl?: T;
  author?: T;
  sourceParty?: T;
  isAIGenerated?: T;
  isDerivative?: T;
  licenseStatus?: T;
  riskLevel?: T;
  usageScope?: T;
  generationPromptSummary?: T;
  referenceNotes?: T;
  notes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regions_select".
 */
export interface RegionsSelect<T extends boolean = true> {
  nameZh?: T;
  nameEn?: T;
  type?: T;
  description?: T;
  sourceType?: T;
  canonLevel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "houses_select".
 */
export interface HousesSelect<T extends boolean = true> {
  nameZh?: T;
  nameEn?: T;
  motto?: T;
  sigilDescription?: T;
  sigil?: T;
  primaryColor?: T;
  secondaryColor?: T;
  seatLocation?: T;
  controlledRegions?: T;
  sourceType?: T;
  canonLevel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "characters_select".
 */
export interface CharactersSelect<T extends boolean = true> {
  nameZh?: T;
  nameEn?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  house?: T;
  titles?:
    | T
    | {
        value?: T;
        id?: T;
      };
  shortBio?: T;
  portrait?: T;
  sourceType?: T;
  canonLevel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  description?: T;
  primaryLocation?: T;
  relatedLocations?: T;
  relatedCharacters?: T;
  relatedHouses?: T;
  relatedAssets?: T;
  order?: T;
  displayDate?: T;
  bookRefLabel?: T;
  showRefLabel?: T;
  isBookEvent?: T;
  isShowEvent?: T;
  isOriginalNote?: T;
  sourceType?: T;
  canonLevel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "storylines_select".
 */
export interface StorylinesSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  description?: T;
  relatedEvents?: T;
  relatedLocations?: T;
  relatedCharacters?: T;
  relatedHouses?: T;
  sourceType?: T;
  canonLevel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  nameZh?: T;
  nameEn?: T;
  aliases?:
    | T
    | {
        value?: T;
        id?: T;
      };
  type?: T;
  region?: T;
  relatedHouses?: T;
  shortDescription?: T;
  longDescription?: T;
  politicalStatus?: T;
  geography?: T;
  mapPosition?:
    | T
    | {
        xPercent?: T;
        yPercent?: T;
        virtualX?: T;
        virtualY?: T;
      };
  iconType?: T;
  nodeLevel?: T;
  visibleZoomRange?:
    | T
    | {
        min?: T;
        max?: T;
      };
  isMvpClickable?: T;
  detailLevel?: T;
  detailSections?:
    | T
    | {
        title?: T;
        body?: T;
        assets?: T;
        id?: T;
      };
  relatedCharacters?: T;
  relatedEvents?: T;
  relatedAssets?: T;
  localMap?: T;
  sourceType?: T;
  canonLevel?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}